---
output: 
  html_document:
    output_dir: docs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE)
library(tidyverse)
```

###  The World Writing System Database {.tabset .tabset-fade .tabset-pills}
Some characters may be displayed incorrectly.

#### about database
Тро-ло-ло

#### search
```{r}
make_link_omniglot <- function(x, link){
  paste("<a href='",
        as.character(link),
        "' target='_blank'>",
        as.character(x),
        "</a>", sep = "")}

make_link_unicode <- function(u){
  paste("<a href='",
        "https://unicode-table.com/en/",
        substr(u,3,6),
        "/' target='_blank'>",
        as.character(u),
        "</a>", sep = "")}

wwsb <- read_csv("database.csv", na = "")
wwsb$script <- make_link_omniglot(wwsb$script, wwsb$omniglot)
wwsb$unicode <- make_link_unicode(wwsb$unicode)
wwsb <- wwsb[,-7]
library(DT)
datatable(wwsb, filter = 'top', rownames = FALSE, options = list(dom = 'tip'), escape = FALSE)
```

#### bibliography
```{r}
bibliography <- read_tsv("bibliography.csv")
bibliography$script <- make_link_omniglot(bibliography$script, bibliography$omniglot)
bibliography <- bibliography[, -4]

library(DT)
datatable(bibliography, filter = 'top', rownames = FALSE, options = list(autoWidth = FALSE), escape = FALSE)
```
